### ISSUE TITLE
is it possible to read from stdin after gtk_main()?

### ISSUE THREAD

**Issue by guyuming76** [padgettr/rfm#8]
I can read from command args, and pipeline input in rfm before gtk_main() is called.

and, with printf, i can print out to stdout.

I can type in the  vt as shown in the picture. But i wonder if there is any way to read what i typed in gtk main loop? so that after rfm read the "cd /tmp" string i typed, we can set_curPath to /tmp

![20230616_13h47m08s_grim](https://github.com/padgettr/rfm/assets/12045548/060272b4-7958-44e1-beba-790ca5a9a2b2)

**Comment by guyuming76** [comment]
i will try whether i can add stdin as an event source

**Comment by guyuming76** [comment]
i will try whether i can add stdin as an event source

**Comment by padgettr** [comment]
Is that for child processes? You can use:
https://docs.gtk.org/glib/func.spawn_async_with_pipes.html
And use a fd to childs stdin?




Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guyuming76** [comment]
i made it with https://github.com/guyuming76/rfm/commit/1b806d86c032903beeffa2e29647952ca00d0bbd

**Comment by padgettr** [comment]
Ah, I see what you mean now!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guyuming76** [comment]
currently, i only deal with "cd command" inside rfm process, i wonder what if i instantiate a child bash process here under rfm process, taking user input, and redirect stdout of child bash here too.

so that i can show  something such as git branch name as command prompt and run bash command such as git checkout here.

**Comment by padgettr** [comment]
Have you considered using either a fifo pipe or a unix domain socket for reading external commands rather than stdin? You could also use dbus, but probably unnecessarily complicated.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guyuming76** [comment]
now, i can type in bash command string in stdin (vio GIOChannel) and execute. 

for example, i can select a text file in iconview and type "nano" in stdin, it will open the text file with nano in the command window(no need to open new window, so i can have only two windows on the screen).

The problem now is how i can use GNU readline or linenoise with GIOChannel so that the commandline type-in experience is more like that in an ordinary VT.  Has anyone combined GIOchannel with libs such as readline?

**Comment by guyuming76** [comment]
i gave up the GIOChannel and created a new thread to run readline, and it works, in the readline git branch in my fork of this repository.

**Comment by padgettr** [comment]
That's great, glad you found a way. Had a quick look at your code, looks OK to me, but when thread is blocked by readline what happens on a signal, e.g. sigterm? Will msg then return as NULL? Can't tell how idle handler function would handle a null, might lead to a segfault on exit?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guyuming76** [comment]
thanks, i made changes in my git readline branch by checking for NULL and ignore SIGINT.

Currently, the architecture is: user input got by readline in seperate thread in rfm, code in rfm gtk main loop will spawn a sync child process to run the readline results with "bash -c". The benefit is that i can insert  selected filenames in iconview into the readline results. But the shortcoming is every new readline start a new bash process, different user commands cannot share same bash variable values.  

I had tried in another git branch to spawn a single bash process, and rfm send readline results through a pipe to this single bash process. One issue is i don't know how to sync rfm with this single piece of user commands execution in this bash process, any idea? 

If i give up readline call in rfm, just spawn a bash process which inherit the stdin, bash can get user command, but this is just like a normal seperate VT and rfm, how can bash here get the status of rfm, such as currently selected file names?

**Comment by padgettr** [comment]
I'm not sure if there is an easy way to do that, I don't know, sorry.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
